project_id = "apmsuigcveqtjzbpfihb"

[functions.webauthn-register]
verify_jwt = false

[functions.webauthn-authenticate]
verify_jwt = false

[functions.create-user]
verify_jwt = false

[functions.login-with-identifier]
verify_jwt = false

[functions.reset-users]
verify_jwt = false

[functions.update-password]
verify_jwt = false

[functions.clone-branch-catalog]
verify_jwt = false
